### ISSUE TITLE
EventStore closed  Connection

### ISSUE THREAD

**Issue by SMMMN** [juicycleff/nestjs-event-store#4]
I have a problem, I don't know exactly why, but the client only manages to connect to the EventStore every now and then in a docker-compose. In the client log I always see the following: 

`[Nest] 39 - 03/04/2020, 1:48:06 PM [NestjsEventStore] EventStore closed! +28745ms
[Nest] 39 - 03/04/2020, 1:48:06 PM [EventStore] Connection 'ES-d4ed476d-4d76-45c2-91f0-3f21da4db8da' was closed. +2ms
[Nest] 39 - 03/04/2020, 1:48:35 PM [NestjsEventStore] EventStore closed! +28650ms
[Nest] 39 - 03/04/2020, 1:49:03 PM [NestjsEventStore] EventStore closed! +28659ms`

I use the EventStore in version 5.0.6.0
My guess is it's the heartbeat timeout. Is it possible to change this on the client side?

**Comment by juicycleff** [comment]
@SMMMN I can try to add support for this

**Comment by juicycleff** [comment]
Readme updated
